### ISSUE TITLE
allow multiple CTT entries?

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-scitt/draft-birkholz-cose-tsa-tst-header-parameter#21]
C2PA allows multiple timestamps from different TSAs to be added back into the COSE envelope.

Do we want to do the same and use an array (or the `one-or-more` [construct from RFC9292](https://www.rfc-editor.org/rfc/rfc9393.html#section-2-13))?

Note that this may slightly complicate processing (and possibly the trust model too) because there would be many "TSA-time"s that need to be considered rather than just one.

Can that aspect of the processing be punted to "local policy"?  In the end, if an application decides to ask for $n$ TSTs, it does so because it supposedly knows what to do with them.

This probably needs some more discussion.

**Comment by thomas-fossati** [comment]
**ACTION** Ask Leonard on the COSE list.

**Comment by henkbirkholz** [comment]
*ACTION* complete be @thomas-fossati dearest. The C2PA on multiple TSTs is rolled back. If there will be no further response to the contrary to https://mailarchive.ietf.org/arch/msg/cose/KfI7Oo7IIFfpK_b6O35sz7G1_8g this issue will be resolved with no changes.

**Comment by henkbirkholz** [comment]
resolved
